version: '3.9'

services:
  db: 
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

  redis:
    image: redis:6.2.5
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    restart: unless-stopped

  fastapi:
    build: 
      context: ./
      dockerfile: Dockerfile
    # command: bash -c "python /app/src/main.py"
    command: bash -c "uvicorn src.main:main_app --host 0.0.0.0 --port 8000 --reload"
    # bash -c "alembic upgrade head && python /app/src/main.py"
    stdin_open: true
    tty: true
    env_file:
      - .env
    # environment:
    #   - PYTHONPATH=/app/src
    volumes:
      - .:/app
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
